
spring:
  application:
    name: api-gateway

server:
  port: 5333

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/
zuul:
  routes:
    provider-auth:
      sensitive-headers:
      custom-sensitive-headers: true
    demo:
      sensitive-headers:
      custom-sensitive-headers: true
    provider-music:
      sensitive-headers:
      custom-sensitive-headers: true
#  开启全部
#  sensitive-headers: