
spring:
  application:
    name: provider-music
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/inori_cloud_music?serverTimezone=UTC
    username: passer
    password: '123456'
    driverClassName: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3001/eureka
server:
  port: 6010
feign:
  hystrix:
    enabled: true