spring:
  application:
    name: consumer-auth
  datasource:
    url: jdbc:mysql://localhost:3306/game?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  mybatis:
    mapperLocations: classpath:mapper/*.xml
server:
  port: 3333
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka