spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/inori_cloud_auth?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: passer
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true