spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/inori_cloud_auth?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: passer
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: passer
#    password: 123456
  cloud:
    stream:
      bindings:
        input:
          destination: sink-channel
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: passer
                password: 123456


eureka:
  client:
    service-url:
      defaultZone: http://localhost:3001/eureka
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8989