spring:
  application:
    name: provider-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Excalibur0w0/inori-cloud-config

server:
  port: 2004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka