spring:
  application:
    name: provider-auth
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/inori_cloud_auth?serverTimezone=UTC
      username: passer
      password: '123456'
      driverClassName: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
server:
  port: 2010
feign:
  hystrix:
    enabled: true