spring:
  application:
    name: provider-auth
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/inori_cloud_auth?serverTimezone=UTC
      username: passer
      password: '123456'
      driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8 # 最大连接数量 负数表示没有限制
        max-wait: -1
        max-idle: 8
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3001/eureka
#    register-with-eureka: false
#    fetch-registry: false
server:
  port: 5010
feign:
  hystrix:
    enabled: true