
spring:
  application:
    name: oauth2
  datasource:
    url: jdbc:mysql://localhost:3306/inori_cloud_auth?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: passer
    password: '123456'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
    register-with-eureka: false
    fetch-registry: false
server:
  port: 9999